# Generated by Django 5.2.10 on 2026-02-10 03:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lecture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='講義名')),
                ('instructor', models.CharField(max_length=100, verbose_name='講師名')),
                ('day_of_week', models.CharField(choices=[('Monday', '月'), ('Tuesday', '火'), ('Wednesday', '水'), ('Thursday', '木'), ('Friday', '金'), ('Saturday', '土'), ('Sunday', '日')], max_length=10, verbose_name='曜日')),
                ('start_time', models.TimeField(verbose_name='開始時刻')),
                ('end_time', models.TimeField(verbose_name='終了時刻')),
                ('classroom', models.CharField(max_length=100, verbose_name='教室')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '講義',
                'verbose_name_plural': '講義',
                'ordering': ['day_of_week', 'start_time'],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='課題名')),
                ('description', models.TextField(blank=True, verbose_name='説明')),
                ('due_date', models.DateTimeField(verbose_name='提出期限')),
                ('priority', models.CharField(choices=[('low', '低'), ('medium', '中'), ('high', '高')], default='medium', max_length=10, verbose_name='優先度')),
                ('status', models.CharField(choices=[('pending', '未提出'), ('submitted', '提出済み'), ('graded', '採点済み')], default='pending', max_length=10, verbose_name='ステータス')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('lecture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='kojin_kouki_kadai.lecture', verbose_name='講義')),
            ],
            options={
                'verbose_name': '課題',
                'verbose_name_plural': '課題',
                'ordering': ['due_date'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submitted_at', models.DateTimeField(verbose_name='提出日時')),
                ('notes', models.TextField(blank=True, verbose_name='備考')),
                ('grade', models.IntegerField(blank=True, null=True, verbose_name='成績')),
                ('feedback', models.TextField(blank=True, verbose_name='フィードバック')),
                ('assignment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='kojin_kouki_kadai.assignment', verbose_name='課題')),
            ],
            options={
                'verbose_name': '提出記録',
                'verbose_name_plural': '提出記録',
                'ordering': ['-submitted_at'],
            },
        ),
    ]
