# Generated by Django 5.2.10 on 2026-02-10 04:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("kojin_kouki_kadai", "0002_remove_submissionrecord_feedback_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Grading",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("grade", models.IntegerField(verbose_name="成績")),
                (
                    "feedback",
                    models.TextField(blank=True, verbose_name="フィードバック"),
                ),
                (
                    "graded_at",
                    models.DateTimeField(auto_now=True, verbose_name="採点日時"),
                ),
                (
                    "submission",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grading",
                        to="kojin_kouki_kadai.submissionrecord",
                        verbose_name="提出記録",
                    ),
                ),
            ],
            options={
                "verbose_name": "採点記録",
                "verbose_name_plural": "採点記録",
                "ordering": ["-graded_at"],
            },
        ),
    ]
